### ISSUE TITLE
[Bug] Rust generation: Implement the serialize trait correctly for the `TupleArray`

### ISSUE THREAD

**Issue by MathieuDutSik** [zefchain/serde-reflection#60]
# 🐛 Bug

The serialize trait is not correctly implemented for generated code in rust.

## To reproduce

The following code does not pass
```yaml
Signature:
  NEWTYPESTRUCT:
    TUPLEARRAY:
      CONTENT: U8
      SIZE: 64
```

The generated rust code is 
```yaml
#[derive(Clone, Debug, PartialEq, PartialOrd, Serialize, Deserialize)]
pub struct Signature(pub [u8; 64]);
```

and it does not compile since there is no serialization/deserialization implementations for `[u8; 64]`.

I think here

## Expected Behavior

I think implementing the trait in the generated code is the way forward.

## System information

The bug is generic.

## Additional context

None.
